version: '3'
services:
  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db
  db:
    image: mongo:4.4.7
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
